Repository chachacreate/chachacreate_legacy, pull requests merged in 2025-09, with the labels that each got.

#31 ✨ feat: 판매자 상품 매출 조회 api 추가
  src/main/java/com/chacha/create/common/dto/product/ProductSalesResponseDTO.java
  src/main/java/com/chacha/create/common/mapper/product/ProductMapper.java
  src/main/java/com/chacha/create/controller/rest/seller/settlement/SettlementManagementRestController.java
  src/main/java/com/chacha/create/service/seller/settlement/SettlementManagementService.java
  src/main/resources/mybatis/mappers/product/productMapper.xml
Labels: ✨ feat

#40 ✨ feat: 주문 상세 상태 업데이트 API 추가(for boot)
  src/main/java/com/chacha/create/common/dto/boot/BootOrderStatusRequestDTO.java
  src/main/java/com/chacha/create/common/mapper/order/OrderDetailMapper.java
  src/main/java/com/chacha/create/controller/rest/BootRestController.java
  src/main/resources/mybatis/mappers/order/orderDetailMapper.xml
Labels: ✨ feat

#42 🐛 fix: 장바구니 전체 삭제 API 오류 수정
  src/main/java/com/chacha/create/controller/rest/store_common/mypage/MyCartRestController.java
Labels: 🐛 fix

#52 🐛 fix: 상품 수정 API 오류 수정
  src/main/java/com/chacha/create/common/dto/product/ProductUpdateDTO.java
  src/main/java/com/chacha/create/controller/rest/seller/product/ProductRestController.java
  src/main/java/com/chacha/create/service/seller/product/ProductService.java
Labels: 🐛 fix

#54 🐛 fix: 메인 전체상품 정렬 조건 추가
  src/main/resources/mybatis/mappers/product/mainPageMapper.xml
Labels: 🐛 fix

#57 🐛 fix: 판매자 주문/발송 상태 확인 로직 복구
  src/main/java/com/chacha/create/controller/rest/seller/order/OrderManagementRestController.java
Labels: 🐛 fix

#63 🐛 fix: 스토어 정보에서 이력 정보 조회되도록 수정
  src/main/java/com/chacha/create/common/mapper/member/SellerMapper.java
  src/main/java/com/chacha/create/service/buyer/storeinfo/StoreInfoService.java
  src/main/resources/mybatis/mappers/member/sellerMapper.xml
Labels: 🐛 fix

#65 ✨ feat: 페이지네이션 기능 추가 및 상태별 조회 로직 개선
  src/main/java/com/chacha/create/common/dto/order/OrderDTO.java
  src/main/java/com/chacha/create/common/mapper/order/OrderMapper.java
  src/main/java/com/chacha/create/controller/rest/seller/order/OrderManagementRestController.java
  src/main/java/com/chacha/create/controller/rest/seller/product/ProductRestController.java
  src/main/java/com/chacha/create/service/seller/order/OrderManagementService.java
  src/main/resources/mybatis/mappers/order/orderMapper.xml
Labels: ✨ feat, 🐛 fix

#78 🐛fix: 마이페이지 주문상세 상태 조회 수정
  src/main/java/com/chacha/create/service/store_common/mypage/MyOrderService.java
  src/main/resources/mybatis/mappers/order/orderMapper.xml
Labels: 🐛 fix
